---
title: "Capstone Project Proposal"
author: "Ava Masucci"
date: "October 6, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Capstone Project Proposal

For my Capstone Project, I want use health data to improve health outcomes in India. With over 1.3 billion people, India is the second most populous country with the third largest economy in the world. My project will primarily focus on reproductive and child health outcomes, highlighting gender inequalities as well as communicable diseases.

My client is a global health organization, public policy organization, or higher education institution. Based on my analysis, my client can distribute resources like vaccines, medical supplies, or healthcare personnel more efficiently. My analysis can also recommend improvements to public health policy in India by predicting health outcomes. I am using a data set from Kaggle called Health Analytics. It contains 26 health indicators (642 variables) from 9 states and 284 districts in India. Some of the variables include: Infant Mortality Rate, Maternal Mortality Ratio, Natal care, Family Planning Methods, Immunization data, Chronic and Childhood Illnesses, and Fertility Rates. 

To solve the problem, I will employ statistical methods to analyze the causes and patterns of poor health outcomes. I will examine key trends in the data such as differences between rural and heavily populated districts. I will also explore the features of the data that are linked to high infant and maternal mortality rates, and other negative health outcomes. Machine learning algorithms will help predict health outcomes by location or other variables. My deliverables are a report or slide deck, a tidy data set, and all code. My report will include easy to read data visualizations that contribute to my data story.  My goal is a project that captivates my client's interest while offering viable solutions to improve health outcomes in India. 

